### ISSUE TITLE
Is there a difference between aloja tool kit and this ?

### ISSUE THREAD

**Issue by nakhanha** [dharmeshkakadia/tpcxbb-hive2#3]
HI ,

I found this intel(https://github.com/intel-hadoop/Big-Data-Benchmark-for-Big-Bench ) big bench toolkit and this, is there any difference ?. I am particularly interested in LLAP  perf test.

Thanks,
Nasrulla

**Comment by dharmeshkakadia** [comment]
Yes. The intel toolkit doesn't support hive2. This fork adds that capability.
